name: Build & Deploy Bodylog Backend

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - "alembic/**"
      - "alembic.ini"
      - "Dockerfile"
      - "requirements.txt"
      - ".github/workflows/deploy.yml"
      - ".dockerignore"
  workflow_dispatch:

concurrency:
  group: bodylog-backend-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bodylog-backend
  CONTAINER_NAME: bodylog-backend
  # GitHub Expressions에서 기본값 연산자(||) 안 먹음 → 원격 스크립트에서 기본값 처리
  PORT: ${{ secrets.APP_PORT }}
  APP_ENV: ${{ secrets.APP_ENV }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: meta
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push
    if: ${{ secrets.SSH_HOST != '' && secrets.SSH_USER != '' && secrets.SSH_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: IMAGE_NAME,CONTAINER_NAME,PORT,APP_ENV
          script: |
            set -euo pipefail

            IMAGE="${IMAGE_NAME}:latest"
            NAME="${CONTAINER_NAME}"
            PORT="${PORT:-8000}"   # 기본값 8000

            echo "[1/5] docker login (optional if registry is public)"
            if [ -n "${DOCKERHUB_USERNAME:-}" ] && [ -n "${DOCKERHUB_TOKEN:-}" ]; then
              echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin || true
            fi

            echo "[2/5] docker pull ${IMAGE}"
            docker pull "${IMAGE}"

            echo "[3/5] stop & remove existing container if any"
            if [ "$(docker ps -aq -f name=^/${NAME}\$)" ]; then
              docker rm -f "${NAME}" || true
            fi

            # (선택) .env 파일 내용을 Secrets로 전달했다면 컨테이너에 적용
            ENV_FILE_OPT=""
            if [ -n "${APP_ENV:-}" ]; then
              echo "[4/5] writing .env from secret"
              echo "${APP_ENV}" > .env
              ENV_FILE_OPT="--env-file .env"
            fi

            echo "[4/5] run new container"
            docker run -d \
              --name "${NAME}" \
              -p ${PORT}:8000 \
              ${ENV_FILE_OPT} \
              --restart unless-stopped \
              "${IMAGE}"

            # (선택) Alembic migrations
            if docker exec "${NAME}" sh -lc 'command -v alembic >/dev/null 2>&1'; then
              echo "[5/5] running alembic upgrade head"
              docker exec "${NAME}" sh -lc 'alembic upgrade head' || true
            else
              echo "[5/5] alembic not found in container. Skipping migrations."
            fi

            echo "✅ Deploy finished."
on:
  workflow_dispatch: