name: "Build & Deploy Bodylog Backend"

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - "alembic/**"
      - "alembic.ini"
      - "Dockerfile"
      - "requirements.txt"
      - ".github/workflows/deploy.yml"
      - ".dockerignore"
  workflow_dispatch:

concurrency:
  group: bodylog-backend-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bodylog-backend
  CONTAINER_NAME: bodylog-backend
  PORT: ${{ secrets.APP_PORT }}
  APP_ENV: ${{ secrets.APP_ENV }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Extract short SHA"
        id: meta
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: "Build & Push (latest + sha)"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # PEM 원문을 쓰는 경우(추천)
      - name: "SSH ping with PEM (if provided)"
        if: ${{ secrets.EC2_HOST != '' && secrets.EC2_SSH_KEY_PEM != '' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          script_stop: true
          script: |
            echo "✅ SSH connected (PEM)"
            whoami
            uname -a

      # Base64 키를 쓰는 경우
      - name: "Write base64 key to file (if provided)"
        if: ${{ secrets.EC2_HOST != '' && secrets.EC2_SSH_KEY_BASE64 != '' }}
        run: |
          printf "%s" "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 -d > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: "SSH ping with key_path (if base64 used)"
        if: ${{ secrets.EC2_HOST != '' && secrets.EC2_SSH_KEY_BASE64 != '' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key_path: ssh_key.pem
          script_stop: true
          script: |
            echo "✅ SSH connected (BASE64)"
            whoami
            uname -a

      # 실제 배포 (PEM 또는 BASE64 어느 쪽이든 하나 성공했으면 진행)
      - name: "Deploy over SSH (PEM)"
        if: ${{ secrets.EC2_HOST != '' && secrets.EC2_SSH_KEY_PEM != '' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          script_stop: true
          envs: IMAGE_NAME,CONTAINER_NAME,PORT,APP_ENV
          script: |
            set -euo pipefail
            IMAGE="${IMAGE_NAME}:latest"
            NAME="${CONTAINER_NAME}"
            PORT="${PORT:-8000}"

            docker pull "${IMAGE}" || true
            if [ "$(docker ps -aq -f name=^/${NAME}\$)" ]; then
              docker rm -f "${NAME}" || true
            fi

            ENV_FILE_OPT=""
            if [ -n "${APP_ENV:-}" ]; then
              echo "${APP_ENV}" > .env
              ENV_FILE_OPT="--env-file .env"
            fi

            docker run -d \
              --name "${NAME}" \
              -p "${PORT}:8000" \
              ${ENV_FILE_OPT} \
              --restart unless-stopped \
              "${IMAGE}"

      - name: "Deploy over SSH (BASE64)"
        if: ${{ secrets.EC2_HOST != '' && secrets.EC2_SSH_KEY_BASE64 != '' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key_path: ssh_key.pem
          script_stop: true
          envs: IMAGE_NAME,CONTAINER_NAME,PORT,APP_ENV
          script: |
            set -euo pipefail
            IMAGE="${IMAGE_NAME}:latest"
            NAME="${CONTAINER_NAME}"
            PORT="${PORT:-8000}"

            docker pull "${IMAGE}" || true
            if [ "$(docker ps -aq -f name=^/${NAME}\$)" ]; then
              docker rm -f "${NAME}" || true
            fi

            ENV_FILE_OPT=""
            if [ -n "${APP_ENV:-}" ]; then
              echo "${APP_ENV}" > .env
              ENV_FILE_OPT="--env-file .env"
            fi

            docker run -d \
              --name "${NAME}" \
              -p "${PORT}:8000" \
              ${ENV_FILE_OPT} \
              --restart unless-stopped \
              "${IMAGE}"
