name: Build & Deploy Bodylog Backend

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "alembic/**"
      - "alembic.ini"
      - "Dockerfile"
      - "requirements.txt"
      - ".github/workflows/deploy.yml"
      - ".dockerignore"
  workflow_dispatch:

concurrency:
  group: bodylog-backend-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bodylog-backend
  CONTAINER_NAME: bodylog-backend
  PORT: ${{ secrets.APP_PORT }}
  APP_ENV: ${{ secrets.APP_ENV }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: meta
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Sanity: check required secrets
        run: |
          set -e
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "EC2_HOST is missing"; exit 1
          fi
          if [ -z "${{ secrets.EC2_SSH_KEY_PEM }}" ]; then
            echo "EC2_SSH_KEY_PEM is missing"; exit 1
          fi
          echo "secrets OK"

      - name: SSH ping (debug)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          debug: true
          script_stop: true
          script: |
            echo "SSH connected"
            whoami
            uname -a
            docker --version || echo "docker not found"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          script_stop: true
          envs: IMAGE_NAME,CONTAINER_NAME,PORT,APP_ENV
          script: |
            set -euo pipefail
            IMAGE="${IMAGE_NAME}:latest"
            NAME="${CONTAINER_NAME}"
            PORT="${PORT:-8000}"

            echo "[1/5] docker pull ${IMAGE}"
            docker pull "${IMAGE}" || true

            echo "[2/5] stop & remove existing container if any"
            if [ "$(docker ps -aq -f name=^/${NAME}\$)" ]; then
              docker rm -f "${NAME}" || true
            fi

            ENV_FILE_OPT=""
            if [ -n "${APP_ENV:-}" ]; then
              echo "${APP_ENV}" > .env
              ENV_FILE_OPT="--env-file .env"
            fi

            echo "[3/5] run new container"
            docker run -d \
              --name "${NAME}" \
              -p "${PORT}:8000" \
              ${ENV_FILE_OPT} \
              --restart unless-stopped \
              "${IMAGE}"

            if docker exec "${NAME}" sh -lc 'command -v alembic >/dev/null 2>&1'; then
              echo "[4/5] alembic upgrade head"
              docker exec "${NAME}" sh -lc 'alembic upgrade head' || true
            fi

            echo "Deploy finished"