# "Prepare SSH key" 스텝 통째로 삭제

- name: "SSH ping (debug)"
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY_PEM }}   # ← 파일 대신 여기!
    debug: true
    script_stop: true
    script: |
      echo "SSH connected"
      whoami || true
      uname -a || true
      command -v docker && docker --version || echo "docker not found"

- name: "Deploy over SSH"
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY_PEM }}   # ← 여기서도 key 사용
    script_stop: true
    envs: IMAGE_NAME,CONTAINER_NAME,PORT,APP_ENV
    script: |
      set -euo pipefail
      IMAGE="${IMAGE_NAME}:latest"
      NAME="${CONTAINER_NAME}"
      PORT="${PORT:-8000}"
      echo "[1/5] docker pull ${IMAGE}"
      docker pull "${IMAGE}" || true
      echo "[2/5] stop & remove existing container if any"
      if [ "$(docker ps -aq -f name=^/${NAME}\$)" ]; then
        docker rm -f "${NAME}" || true
      fi
      ENV_FILE_OPT=""
      if [ -n "${APP_ENV:-}" ]; then
        echo "${APP_ENV}" > .env
        ENV_FILE_OPT="--env-file .env"
      fi
      echo "[3/5] run new container"
      docker run -d --name "${NAME}" -p "${PORT}:8000" ${ENV_FILE_OPT} --restart unless-stopped "${IMAGE}"
      if docker exec "${NAME}" sh -lc 'command -v alembic >/dev/null 2>&1'; then
        echo "[4/5] alembic upgrade head"
        docker exec "${NAME}" sh -lc 'alembic upgrade head' || true
      fi
      echo "Deploy finished"
